# Generated by Django 5.2.17 on 2026-09-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('achievement', models.CharField(max_length=255)),
                ('year', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('photo_static_path', models.CharField(max_length=255)),
                ('photo_alt', models.CharField(max_length=255)),
                ('photo_width', models.PositiveIntegerField()),
                ('photo_height', models.PositiveIntegerField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('source_key', models.SlugField(blank=True, default=None, null=True, unique=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
