# Generated by Django 5.2.17 on 2026-09-14 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_experience_portfolio_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
